apiVersion: v1
kind: Secret
metadata:
  name: cast-db-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.castDb.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.castDb.password | b64enc }}
  POSTGRES_DB: {{ .Values.castDb.database | b64enc }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cast-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.castDb.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cast-db
  labels:
    app: cast-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cast-db
  template:
    metadata:
      labels:
        app: cast-db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.castDb.image }}
          envFrom:
            - secretRef:
                name: cast-db-secret
          volumeMounts:
            - name: cast-db-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
                cpu: 200m
                memory: 512Mi
            limits:
                cpu: 1
                memory: 1Gi
      volumes:
        - name: cast-db-storage
          persistentVolumeClaim:
            claimName: cast-db-pvc
