apiVersion: v1
kind: Service
metadata:
  name: cast-service
  labels:
    app: cast-service
spec:
  type: ClusterIP
  selector:
    app: cast-service
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
