apiVersion: v1
kind: Secret
metadata:
  name: movie-db-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.movieDb.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.movieDb.password | b64enc }}
  POSTGRES_DB: {{ .Values.movieDb.database | b64enc }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movie-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.movieDb.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-db
  template:
    metadata:
      labels:
        app: movie-db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.movieDb.image }}
          envFrom:
            - secretRef:
                name: movie-db-secret
          volumeMounts:
            - name: movie-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: movie-db-storage
          persistentVolumeClaim:
            claimName: movie-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: movie-db
spec:
  ports:
    - port: 5432
  selector:
    app: movie-db
