replicaCount: 3

image:
  repository: rachidtakni/fastapiapp
  tag: "latest"

resources:
  limits:
    cpu: "1"
    memory: "2Gi"

ingress:
  enabled: true
  host: prod-app.cours-datascientest1.abrdns.com # url app prod
