replicaCount: 2

image:
  repository: rachidtakni/fastapiapp
  tag: "latest"

resources:
  requests:
    cpu: 20m
  limits:
    cpu: 200m


ingress:
  enabled: true
  host: qa-app.cours-datascientest1.abrdns.com # url QA 
