replicaCount: 2

image:
  repository: rachidtakni/fastapiapp
  tag: "latest"

resources:
  limits:
    cpu: "300m"
    memory: "512Mi"

ingress:
  enabled: true
  host: qa-app.cours-datascientest1.abrdns.com # url QA 
